const config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#2f2926",
        "secondary-container": "#e3aa00",
        "glow-amber": "rgba(234, 88, 12, 0.4)",
        "secondary": "#ffc640",
        "on-surface": "#ece0dc",
        "on-background": "#ece0dc",
        "on-primary-fixed": "#370e00",
        "surface-bright": "#3e3835",
        "primary-fixed-dim": "#ffb599",
        "on-secondary-fixed-variant": "#5c4300",
        "tertiary-container": "#4d8eff",
        "primary-fixed": "#ffdbce",
        "on-primary-fixed-variant": "#7f2b00",
        "on-primary-container": "#4f1700",
        "background": "#171210",
        "inverse-on-surface": "#352f2d",
        "error": "#ffb4ab",
        "border-subtle": "rgba(234, 88, 12, 0.15)",
        "tertiary": "#adc6ff",
        "tertiary-fixed-dim": "#adc6ff",
        "surface-container-highest": "#3a3331",
        "surface-elevated": "#1c1715",
        "surface": "#171210",
        "inverse-primary": "#a73a00",
        "primary-container": "#f66018",
        "on-tertiary-fixed-variant": "#004395",
        "tertiary-fixed": "#d8e2ff",
        "on-secondary": "#402d00",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#201a18",
        "on-secondary-container": "#5a4100",
        "surface-base": "#171210",
        "on-tertiary-fixed": "#001a42",
        "surface-tint": "#ffb599",
        "on-secondary-fixed": "#261a00",
        "secondary-fixed": "#ffdf9f",
        "surface-container": "#241e1c",
        "surface-dim": "#171210",
        "surface-container-lowest": "#120d0b",
        "outline-variant": "#5a4138",
        "surface-variant": "#3a3331",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#f9bd22",
        "on-tertiary-container": "#00285d",
        "code-gray": "#9ca3af",
        "on-surface-variant": "#e2bfb2",
        "on-error": "#690005",
        "inverse-surface": "#ece0dc",
        "outline": "#a98a7e",
        "on-primary": "#5a1c00",
        "on-tertiary": "#002e6a",
        "primary": "#ffb599"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "container-margin": "24px",
        unit: "4px",
        gutter: "16px",
        "density-comfy": "24px",
        "density-tight": "8px"
      },
      fontFamily: {
        "headline-lg": ["Geist", "sans-serif"],
        "headline-xl": ["Geist", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "mono-label": ["'JetBrains Mono'", "monospace"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "mono-code": ["'JetBrains Mono'", "monospace"]
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "mono-label": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "mono-code": ["13px", { lineHeight: "20px", fontWeight: "450" }]
      }
    },
  },
  plugins: [],
}

export default config